package com.example.smsphone;

public class Comons {
    public static final String str = "http://member.1688.com//member/ajax/send_identity_code_by_mobile.do?callback=jQuery172007067019236274064_1376100939244&mobile=%phone_number%&area=86&isBizMobile=true," +
            "https://affiliate-program.amazon.com/gp/associates/apply/assoc-ivs.html?phoneNumber=%2B86%phone_number%&operation=start&ts=1376044348191," +
            "http://authleqr.sdo.com/lars/send-login-validate-code.jsaonp?callback=jQuery16206594030656120524_1341237419373&userId=%phone_number%," +
            "http://member.tiancity.com/handler/GetPhoneRegAuthCodeHandler.ashx?a=135&userid=%phone_number%," +
            "https://affiliate-program.amazon.com/gp/associates/apply/assoc-ivs.html?phoneNumber=%2B86%phone_number%&operation=start&ts=1376099658512," +
            "http://i.360.cn/smsApi/sendsmscode?account=%phone_number%&condition=2&r=0.8326570473673853&callback=QiUserJsonP1354551431282," +
            "https://affiliate-program.amazon.com/gp/associates/apply/assoc-ivs.html?phoneNumber=%2B86%phone_number%&operation=start&ts=137606625123," +
            "http://passport.cnyw.net//ajax.php?action=getverify&mobile=%phone_number%," +
            "http://www.kunlun.com/?act=ajax.registGetMobileCode&mobile=%phone_number%&type=regist," +
            "http://www.vko.cn/sendmobile.html?phone=%phone_number%&{}&_=1355879411734," +
            "http://www.66call.com/register.aspx?__EVENTTARGET=&__EVENTARGUMENT=&__LASTFOCUS=&__VIEWSTATE=%2FwEPDwUKLTYzNzEwOTYxOA9kFgJmD2QWDAIFDw8WAh4EVGV4dAULMTU5NTAxMjgwMzZkZAIHDw8WBh8ABQblj6%2FnlKgeCENzc0NsYXNzBQ5yX2NfY19yX2NoZWNrMR4EXyFTQgICZGQCDQ8PZBYCHgV2YWx1ZQUJamlhbmdsaWxpZAIPDw8WBh8ABQbpgJrov4cfAQUOcl9jX2Nfcl9jaGVjazEfAgICZGQCEQ8PZBYCHwMFCWppYW5nbGlsaWQCEw8PFgYfAAUG6YCa6L%2BHHwEFDnJfY19jX3JfY2hlY2sxHwICAmRkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYCBQxJbWFnZUJ1dHRvbjEFDEltYWdlQnV0dG9uMoC6NmiwUtO9MaSDo%2BblDqWjloj5&txtact=%phone_number%&hidfoc=&hidisOk=1&txtpwd=jianglili&txtrepwd=jianglili&txtcode=&ImageButton1.x=59&ImageButton1.y=11," +
            "https://affiliate-program.amazon.com/gp/associates/apply/assoc-ivs.html?phoneNumber=%2B86%phone_number%&operation=start&ts=%phone_number%," +
            "http://register.sdo.com/gaea/SendPhoneMsg.ashx?page=REG&mobile=%phone_number%," +
            "http://wap.easou.com/sms.e?name=%e8%93%9d%e8%93%9d%e5%a4%a9%e7%a9%ba&mobile=%phone_number%&action=sms&usid=9&," +
            "http://www.gewara.com/ajax/mobile/register.xhtml?mobile=%phone_number%&captchaId=&captcha=," +
            "http://w.sohu.com/t2/tologin.do?mnd=%phone_number%&qr=1," +
            "http://www.66call.com/register.aspx?__EVENTTARGET=&__EVENTARGUMENT=&__LASTFOCUS=&__VIEWSTATE=%2FwEPDwUKLTYzNzEwOTYxOA9kFgJmD2QWDAIFDw8WAh4EVGV4dAULMTU5NTAxMjgwMzZkZAIHDw8WBh8ABQblj6%2FnlKgeCENzc0NsYXNzBQ5yX2NfY19yX2NoZWNrMR4EXyFTQgICZGQCDQ8PZBYCHgV2YWx1ZQUJamlhbmdsaWxpZAIPDw8WBh8ABQbpgJrov4cfAQUOcl9jX2Nfcl9jaGVjazEfAgICZGQCEQ8PZBYCHwMFCWppYW5nbGlsaWQCEw8PFgYfAAUG6YCa6L%2BHHwEFDnJfY19jX3JfY2hlY2sxHwICAmRkGAEFHl9fQ29udHJvbHNSZXF1aXJlUG9zdEJhY2tLZXlfXxYCBQxJbWFnZUJ1dHRvbjEFDEltYWdlQnV0dG9uMoC6NmiwUtO9MaSDo%2BblDqWjloj5&txtact=%phone_number%&hidfoc=&hidisOk=1&txtpwd=zhasini&txtrepwd=zhasini&txtcode=&ImageButton1.x=59&ImageButton1.y=11," +
            "http://wap.dm.10086.cn/X/o/3455101/447117/mva0?a=/enduser/querySMSValiCodeByWap20.action&templateDir=template&theme=simple&name=querySMSValiCode&id=querySMSValiCode&downId=&operateType=1&isPass=true&user.accountName=%phone_number%&Submit=%E4%B8%8B%E4%B8%80%E6%AD%A5," +
            "http://a.10086.cn/pams2/s/s.do?c=204&j=l&lpt=1&mobile=%phone_number%&p=72," +
            "http://read.10086.cn/www/firstpage/getValidateCode.action?phone=%phone_number%&sf=0," +
            "http://read.10086.cn/www/NiceNameAjax?msisdn=%phone_number%&e_cm=cmmobile," +
            "https://cmpay.10086.cn/service/send_chk_no.xhtml?REG_MBL_NO=%phone_number%&SMS_CD=URM001&typ=Y&r=0.9636801626045905," +
            "https://feixin.10086.cn/account/RegisterLv3Ajax?stype=m&stext=%phone_number%," +
            "http://my.feixin.10086.cn/password/findpasswordvalidate?type=0&account=%phone_number%," +
            "http://218.206.191.106/idm/usermgr/usernameCheck?mobilePhone=%phone_number%," +
            "http://go.10086.cn/index.do?method=doReg&mobile=%phone_number%&source=reg," +
            "http://www.keepc.com/registerForMobileForCode.act?mobileNo=%phone_number%," +
            "http://wap.cmread.com/sso/oauth2/msisdnRegister?e_l=1&f=7718&pg=221&msisdn=%phone_number%&passwd=1415926," +
            "https://passport.jd.com/emReg/isMobileEngaged?mobile=%phone_number%&r=0.08241349037594953," +
            "http://shoujibao.net/pams2/m/s.do?j=l&c=31879&p=73&mobile=%phone_number%&password=1415926," +
            "http://www.huggieshappyclub.com/Handler/Vcode.ashx?mobile=%phone_number%," +
            "http://wap.buidq.com/wap/webcallService.aspx?tel=%phone_number%," +
            "http://www.uwewe.com/get/IsUser.aspx?phone=%phone_number%&quhao=86," +
            "http://www.uwewe.com/get/SendMessage.aspx?phone=%phone_number%&ccode=86&type=1," +
            "http://www.66call.com/forgetpwd.aspx?ScriptManager1=UpdatePanel1|ImageButton2&__EVENTTARGET=&__EVENTARGUMENT=&__VIEWSTATE=%2FwEPDwULLTExMjY2ODE5MTgPFgYeCFRpbWVTcGFuBqpmMwD38M%2BIHgRjb2RlBQQ0MjY1HgRhY2N0BQsxNTgzODgwMjA0MmQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgMFDEltYWdlQnV0dG9uMgUMSW1hZ2VCdXR0b24xBQxJbWFnZUJ1dHRvbjPdI0AXCiz2XIYks0CPZpmkSSEMDg%3D%3D&txtacct=%phone_number%&txtcode=7426&txtpwd=&txtrepwd=&ImageButton2.x=76&ImageButton2.y=18," +
            "http://www.wcall.net/ajax/send_captcha.jsp?mobile=86%phone_number%," +
            "http://www.uwewe.com/wap/reg.aspx?__VIEWSTATE=%2FwEPDwUKLTg3MDQ4MjcyNGRkTWAEkK5GOtWg8l1At7LuQLJsrtk%3D&__EVENTVALIDATION=%2FwEWBwLf79jTDQL7h7XWDwKd%2B7q4BwLinreAAgLChPzDDQK7q7GGCAKM54rGBiIS9Dt7i1j1h%2BDtH9EcyHIWJVZf&txtacct=%phone_number%&txtpwd=&txtRepwd=&txtCode=&Button2=%E8%AF%AD%E9%9F%B3%E8%8E%B7%E5%8F%96%E9%AA%8C%E8%AF%81%E7%A0%81http://www.gewara.com/ajax/mobile/register.xhtml?mobile=%phone_number%&captchaId=&captcha=," +
            "http://www.gewara.com/checkMember.xhtml?tag=mobile&itemvalue=%phone_number%," +
            "http://www.dianping.com/ajax/json/account/reg/mobile/send?m=%phone_number%," +
            "http://www.ushi.com/openRegU!checkNumber.jhtml?basicProfile.mobile=%phone_number%," +
            "http://www.efala.net/newfindpwbysms.flow?byname=%phone_number%," +
            "http://zj.189.cn/zjpr/member/authentication/sendValidatePhone.html?phone=%phone_number%," +
            "http://weibo.com/signup/v5/formcheck?type=mobile&value=%phone_number%&__rnd=1363496469546," +
            "http://api.open.uc.cn/cas/register/mobi/resendVCode?uc_param_str=einisivelafrpf&client_id=20033&from=cas&mobi=%phone_number%," +
            "http://ptlogin.4399.com/ptlogin/sendRegPhoneCode.do?phone=%phone_number%&appId=www_home&v=1&v=1," +
            "http://i.youku.com/u/bindMobile?__rt=1&__ro=&mobile=%phone_number%," +
            "https://safe.renren.com/actions/changesafemobile/sendmobilecaptcha?ajax-type=json&token=1ZhR7iv65SgaNXliuA7mujgTO3s3k1CL&mobile=%phone_number%&requestToken=496404876&_rtk=e95787e6," +
            "http://service.zol.com.cn/user/ajax/sendMsgCode.php?phone=%phone_number%," +
            "https://login.vancl.com/login/BeginRegister.ashx?action=sendmobilecode&key=%phone_number%&validatecode=&_=1363498730859," +
            "http://passport.eastmoney.com/chkphone.aspx?flag=check¶m=%phone_number%," +
            "http://passport.eastmoney.com/chkphone.aspx?flag=resend¶m=%phone_number%," +
            "http://passport.cntv.cn/mobileRegister.do?msisdn=%phone_number%&verfiCodeType=1&method=getRequestVerifiCode," +
            "http://register.zhenai.com/register/validateMobile.jsps?mobile=%phone_number%," +
            "http://reg.jiayuan.com/libs/xajax/reguser.server.php?processSendOrUpdateMessage&xajax=processSendOrUpdateMessage&xajaxargs%5B%5D=%3Cxjxquery%3E%3Cq%3Emobile%3Dd$%3C%2Fq%3E%3C%2Fxjxquery%3E&xajaxargs%5B%5D=mobile&xajaxr=1363500615734," +
            "https://passport.jd.com/emReg/sendMobileCode?mobile=%phone_number%&r=0.9010949897739119," +
            "https://member.suning.com/emall/SNCellPhoneRegisterCmd?actionType=reSendValCode&logonId=%phone_number%&URL=SNUserRegisterComfirmView&_=1363500974671," +
            "http://account.iqiyi.com/security/secret/mobile/adm.action?time=1363501090218&mobile=%phone_number%," +
            "http://www.skywldh.com/registerForMobileForCode.act?mobileNo=%phone_number%&smSecurityCode=," +
            "http://wap.skywldh.com/index.php?register&flag=flag&phone=%phone_number%&mss=on," +
            "http://zg51.net/web/customer/forgetPwd_up.asp?customermobile=%phone_number%&verify=01f735f97f1af959&checkcodeflag=1," +
            "http://www.qqvoice.com/free/getExpCode.do?_isAjaxRequest=true&phonemail=%phone_number%&type=1&randvalue=," +
            "http://www.feiin.com/findAccountInfoByAccount.act?mobile=%phone_number%," +
            "http://wap.feiin.cn/index.php?register?phone=%phone_number%," +
            "http://www.feiin.cn/bindMobileCode.act?account=%phone_number%&quhao=0086," +
            "http://www.139talk.com/user/regnum.html?phone=%phone_number%&type=1&key=ofoedsv0oeg6aari1m3ig0nsc5," +
            "http://www.139talk.com/invite/invitesms.html?phone=%phone_number%&key=ofoedsv0oeg6aari1m3ig0nsc5," +
            "http://www.139talk.com/invite/regnum.html?phone=%phone_number%&type=1&key=ofoedsv0oeg6aari1m3ig0nsc5," +
            "http://www.139talk.com/invite/register.html?p=cGhvbmV8MTU4Mzg4MDIwNDJ8Y2hrY29kZXw4OTczfGRhdGV8MjAxMy0wMy0xNw==," +
            "http://www.139talk.com/download/smsdownload.html?popPhone=%phone_number%&phoneType=Iphone&popKey=ofoedsv0oeg6aari1m3ig0nsc5," +
            "http://www.159talk.com/user/regnum.html?phone=%phone_number%&type=1&key=h5u9albk8oveqm17rfo6kvo226," +
            "http://my.tv.sohu.com/user/reg/getmstatus.do?passport=%phone_number%," +
            "http://sso.letv.com/user/mobileRegCode/mobile/%phone_number%/mobilecodeletvid/k961601363512388," +
            "http://register.sdo.com/gaea/SendPhoneMsg.ashx?page=REG&mobile=%phone_number%," +
            "http://download.feixin.10086.cn/download/downloadFLToMobile.action?id=50&no=%phone_number%&isCheckCode=1," +
            "http://my.feixin.10086.cn/password/sendfindpasswordsms?MobileNo=%phone_number%," +
            "http://f.10086.cn/im5/register/checkMobile.action?mobileNo=%phone_number%," +
            "http://zc.qq.com/cgi-bin/bd/send_sms?acc=%phone_number%&bkn=1656136920&v=0.6187287989762199," +
            "http://weibo.com/signup/v5/formcheck?type=sendsms&value=%phone_number%&__rnd=1364610012046http://hm.baidu.com/hm.gif?cc=1&ck=1&cl=16-bit&ds=1280x800&ep=%E8%8E%B7%E5%8F%96%E9%AA%8C%E8%AF%81%E7%A0%81*%E7%82%B9%E5%87%BB&et=4&fl=11.6&ja=1&ln=zh-cn&lo=0&nv=1&rnd=2125197633&si=4cd143d67831005438c65f586314c582&st=3&su=http://club.autohome.com.cn%2Fbbs%2Fthread-c-148-2031217-1.html&v=1.0.40&lv=1&api=8_0&tt=%E7%94%A8%E6%88%B7%E6%B3%A8%E5%86%8C_%E6%B1%BD%E8%BD%A6%E4%B9%8B%E5%AE%B6," +
            "https://www.qianwang365.com/uc/ajax/obtainSecurityCode4Regist.html?username=%phone_number%," +
            "http://www.efala.net/getcode.flow?phone=%phone_number%&cardno=&code=&," +
            "http://passport.wanmei.com/NoteAction.do?method=sendRegCode&mobile=%phone_number%," +
            "http://biz.b2b.cn/member/SendCode.ashx?temptime=1365067755281&m=%phone_number%," +
            "http://www.kunlun.com/index.php?act=ajax.checkUsername&user_name=%phone_number%," +
            "http://reg.email.163.com/unireg/call.do?cmd=added.mobileverify.sendAcode&mobile=%phone_number%&uid=%phone_number%%40163.com&mark=mobile_start," +
            "http://passport.eastmoney.com/chkphone.aspx?flag=resend¶m=%phone_number%," +
            "http://user.syyx.com/ajax/users/checkusername.aspx?u=%phone_number%&r=0.42031912299903756," +
            "http://www.keepc.com/findAccountInfoByAccount.act?mobile=%phone_number%," +
            "http://service.zol.com.cn/user/ajax/sendMsgCode.php?phone=%phone_number%," +
            "http://gwpassport2.woniu.com/v2/checkusername?jsoncallback=jQuery172013263149083391296_1365068016801&username=%phone_number%&_=1365068030671," +
            "http://passport.upaidui.com/mobiles/send_validation_code?mobile_number=%phone_number%," +
            "http://user.51wan.com/reg_index_check_0.html?type=username&is=mobile&username=%phone_number%," +
            "http://interface.game.renren.com/ActivityCenter/?catalog=plugins&gameid=all&aname=reg&method=reg.subUserInfo&mobile=%phone_number%&callback=jQuery17204292543791520399_1365068164751&_=1365068180406," +
            "http://my.xoyo.com/register/NewIsExist/?uid=%phone_number%," +
            "http://member.tiancity.com/handler/GetPhoneRegAuthCodeHandler.ashx?a=0.016777698590329404&userid=%phone_number%," +
            "http://member.changyou.com/register/checkPhoneIsUsed.do?securityPhone=%phone_number%," +
            "http://www.game5.com/member/sendRegisterVerifyCode?reg_mobile=%phone_number%," +
            "http://passport.kongzhong.com/acc.do?m=sendPhoneVcodeFast&callback=jQuery17200752385214847075_1364445730228&phone=%phone_number%&smsvcode=%E8%BE%93%E5%85%A5%E6%89%8B%E6%9C%BA%E8%8E%B7%E5%8F%96%E7%9A%84%E9%AA%8C%E8%AF%81%E7%A0%81&_=1364445764320," +
            "http://www.pceggs.com/myaccount/mobile_ajax.aspx?refresh=0&i_mobileNo=%phone_number%," +
            "http://www.9dapai.com/SMSAuthentication/SMSAuthenticationPage.aspx/btnGenerateCheckCode_Click?(Content)=%7Bcellnum%3A'%phone_number%'%7D," +
            "http://www.veryzhun.com/ajax/register.asp?mobile=%phone_number%&areacode=86," +
            "http://wap.callda.com/register_2.jsp?phoneNumber=%phone_number%," +
            "http://www.200call.com/index.php?action=vphone?uphone=%phone_number%," +
            "http://wap.12580call.cn/index.php?register&phone=%phone_number%," +
            "http://w.yunpan.360.cn/intf.php?method=Sms.issue&qid=177256015&devtype=box&v=1.9.2.1245&devid=5b5b55bfc9f1f3113963b1f1350adc65&devname=&rtick=6969759&sign=aa8d029e8036f3f9d555956388dc4c57&ofmt=xml&pid=home&mobile=%phone_number%&contype=mdu&token=3708649921.6.95535003.177256015.1366401362," +
            "http://member.tiancity.com/handler/GetPhoneRegAuthCodeHandler.ashx?a=0.6334787302703851&userid=%phone_number%," +
            "http://passport.eastmoney.com/chkphone.aspx?flag=resend¶m=%phone_number%," +
            "http://passport.17u.cn/Member/RegisterHandler.ashx?action=phone&phone=%phone_number%&iid=0.6011805873638694," +
            "http://3g.163.com/t/signup.do?mobile=%phone_number%&sub=%E8%8E%B7%E5%8F%96%E5%AF%86%E7%A0%81%E7%9F%AD%E4%BF%," +
            "http://m.mail.163.com/reg.s?regtype=mobile&method=registerMobile&mobile_num=%phone_number%&password=testtest&password2=testtest&action=%E6%8F%90%E4%BA%A4%E6%B3%A8%E5%86%8C%E4%BF%A1%E6%81%AF=400," +
            "http://account.jzyx.com/common/send-sms.html?tel=%phone_number%," +
            "http://t.sdo.com/home/SendSms?mobile=%phone_number%," +
            "http://txz.sdo.com/common/msgsend/?m=%phone_number%&t=2&method=SendAPPDownLoadSMSCallback&fromid=weblogin&r=0.9407026621045355," +
            "https://mcas.sdo.com/authen/checkAccountType.jsonp?callback=checkAccountType_JSONPMethod&inputUserId=%phone_number%," +
            "http://authleqr.sdo.com/lars/check-account-types.jsonp?callback=jQuery16202903677772887056_1353757072377&userId=%phone_number%&_=1353757193062," +
            "https://reg.95538.cn/userreg/AjaxHandler.ashx?method=getPhoneCode?mobilePhone=%phone_number%&type=0," +
            "http://u.baidu.com/?module=default&controller=Reg&action=sendSMS&b1350745948890=1&mobile=%phone_number%&appid=3&ucname=huisexinxi," +
            "http://as.baidu.com/a/msg?act=sendtomobile&f=topic_3001_2_0&mobile=%phone_number%&docid=1439803&ctime=1353852949890," +
            "http://as.baidu.com/a/msg?act=sendtomobile&f=web_alad_6%40next%40software_1003_6&mobile=%phone_number%&docid=1346020&ctime=1350747592671," +
            "http://api.pengyou.com/json.php?mod=mobilebind&act=sendsms&mobile=%phone_number%&g_tk=null," +
            "http://www.maiduo.com/handler/Register/Register.ashx?act=check&mobile=%phone_number%&checkCode=undefined," +
            "http://www.sinosig.com/auth/regist_resetMsg.action?sso_userName=%phone_number%&isAjaxSubmit=true," +
            "http://www.pubyun.com/accounts/signup_vcode/4449056/?mobile=%phone_number%," +
            "http://dealer.autohome.com.cn/Handler/SendMessage.ashx?action=sendcode&mob=%phone_number%," +
            "http://yuyue.shdc.org.cn/User/ajaxSendConfirmCode.aspx?mobile=%phone_number%," +
            "http://reg.ztgame.com/registe/mobilePhoneRegister?type=isBindPhoneNum&phoneNum=%phone_number%," +
            "http://www.baixing.com/ajax/auth/sendCode/?type=resetPassword&mobile=%phone_number%," +
            "http://mail.sina.com.cn/cgi-bin/phonecode.php?phonenumber=%phone_number%," +
            "http://passport.q.com.cn/register/index/ajaxcheckmobile/?mobile=%phone_number%," +
            "http://yun.baidu.com/account/v1/api/sendacodenormal?dest=%phone_number%," +
            "https://reg.passport.the9.com/api/chk_loginname?loginname=%phone_number%&accounttype=reg_mobile," +
            "https://login.sina.com.cn/signup/check_user.php?format=json&from=mobile&name=%phone_number%," +
            "http://js.ac.10086.cn/jsauth/reg?method=sendVerCode&=%phone_number%," +
            "http://my.xoyo.com/register/isExist/0.8101254514227967?uid=%phone_number%&type=mobile," +
            "http://member.changyou.com/register/checkPhoneIsUsed.do?securityPhone=%phone_number%," +
            "https://reg.91.com/AjaxAction/AC_register.ashx?action=verifyusernameofmobile&txtUserNameOfMobile=%phone_number%," +
            "http://211.136.93.21/hfwebbusi/pay/saveOrder.do?mobileId=%phone_number%," +
            "http://passport.wanmei.com/NoteAction.do?method=sendRegCode?mobile=%phone_number%," +
            "http://authleqr.sdo.com/lars/check-account-types.jsonp?callback=jQuery16203658856788579764_1366925187811&userId=%phone_number%&_=1366925195670," +
            "http://www.guahao.com/validcode/json/mobile/%phone_number%/REG_MOBILE/cebaf071614ac29f9ad6c692b474a46f?_=1366925898545," +
            "http://chinatelecom.zc.qq.com/cgi-bin/send_sms?phonenum=%phone_number%&stype=1," +
            "http://cas.sdo.com/authen/sendPhoneCheckCode.jsonp?callback=sendPhoneCheckCode_JSONPMethod&inputUserId=%phone_number%&type=3&appId=201&areaId=0&serviceUrl=," +
            "http://www.1732.com/public/ajax.aspx?app=resendcode&bindaccount=%phone_number%," +
            "http://sign.kting.cn/register/getphoneverify/phone/%phone_number%," +
            "http://m.xs8.cn/user/quick_signup.html?mobile=%phone_number%," +
            "http://bbs.360che.com/ajax1.php?action=ds21&mobilenum=%phone_number%&inajax=1&ajaxtarget=ts," +
            "http://pass.ledu.com/reg/mobilecode?type=reg&mobile=%phone_number%&r=0.7577109599155907," +
            "http://www.52callme.com/Handler/SendVerifyCodeHandler.ashx?m=%phone_number%," +
            "http://sso.letv.com/user/mobileRegCode/mobile/%phone_number%/mobilecodeletvid/c326961366927138," +
            "http://www.sinosig.com/auth/regist_refresh.action?sso_userName=%phone_number%&resetSend=1," +
            "https://sn.ac.10086.cn/sendMsgRequest?mobileNumber=%phone_number%," +
            "https://fj.ac.10086.cn/SMSCodeSend?mobileNum=%phone_number%&validCode=0000&errorurl=https://fj.ac.10086.cn/4login/errorPage.jsp&name=menhu," +
            "https://fj.ac.10086.cn/SMSCodeSend?mobileNum=%phone_number%&validCode=0000&errorurl=http://www.fj.10086.cn:80/service/login/send.jsp," +
            "https://fj.ac.10086.cn/ssouser/sendMessage.do?mobileno=%phone_number%," +
            "http://www.gs.10086.cn/gs_obsh_service/actionDispatcher.do?userMobile=%phone_number%," +
            "https://sn.ac.10086.cn/sendMsgRequest?code=%E7%82%B9%E5%87%BB%E8%8E%B7%E5%8F%96%E9%AA%8C%E8%AF%81%E7%A0%81&mobileNumber=%phone_number%," +
            "https://js.ac.10086.cn/jsauth/dzqd/pagSendDypass?umobile=%phone_number%," +
            "http://gd.10086.cn/ngcrm/hall/SendRandomSms.action?mobile=%phone_number%&isReRequest=false," +
            "http://liao.189.cn/ECP-Portals/phoneDown/download.do?phone=%phone_number%," +
            "https://ecplive.cn/reg/servlet/ivrInvokeServlet?number=%phone_number%&flagNum=3";
}
